services:
  web:
    container_name: "web"
    build:
      dockerfile: "./container/web/Dockerfile"
    ports: # ポートフォワード
      - "8080:80" # ホスト側のポート:コンテナ側のポート
    volumes:
      - "./src:/var/www/html" # ホスト側のディレクトリ:コンテナ側のディレクトリ

  php:
    container_name: "php"
    build:
      dockerfile: "./container/php/Dockerfile"
    volumes:
      - "./src:/var/www/html" # ホスト側のディレクトリ:コンテナ側のディレクトリ

  db:
    container_name: "db"
    build:
      dockerfile: "./container/db/Dockerfile"
    platform: linux/x86_64
    ports:
      - "3306:3306" # ホスト側のポート:コンテナ側のポート
    environment:  # 環境変数
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    # volumes:
    #   - "./container/db/data:/var/lib/mysql" # ホスト側のディレクトリ:コンテナ側のディレクトリ