services:
  web:
    container_name: "web"
    build:
      dockerfile: "./container/web/Dockerfile"
    ports: # ポートフォワード
      - "9000:80" # ホスト側のポート:コンテナ側のポート
    volumes:
      - "./src:/var/www/html" # ホスト側のディレクトリ:コンテナ側のディレクトリ

  php:
    container_name: "php"
    build:
      dockerfile: "./container/php/Dockerfile"
    volumes:
      - "./src:/var/www/html" # ホスト側のディレクトリ:コンテナ側のディレクトリ

  db:
    container_name: "db"
    build:
      dockerfile: "./container/db/Dockerfile"
    ports:
      - "3306:3306" # ホスト側のポート:コンテナ側のポート
    environment:  # 環境変数
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    volumes:
      - "db-data:/var/lib/mysql" # ホスト側のディレクトリ:コンテナ側のディレクトリ

  pma:
    container_name: "pma"
    image: phpmyadmin/phpmyadmin:5.2.1
    platform: linux/amd64
    ports:
      - "4000:80"
    environment:
      - "PMA_HOST=db"
      - "PMA_USER=laravel"
      - "PMA_PASSWORD=password"
      - "PMA_ARBITRARY=1"
    depends_on:
      - db

volumes:
  db-data:
